# Generated by Django 4.2.7 on 2026-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu data diterima')),
                ('wind_speed', models.FloatField(default=0.0, help_text='Kecepatan angin dalam knot')),
                ('pitch', models.FloatField(default=0.0, help_text='Sudut pitch dalam derajat')),
                ('roll', models.FloatField(default=0.0, help_text='Sudut roll dalam derajat')),
                ('tilt_rate', models.FloatField(default=0.0, help_text='Laju kemiringan dalam derajat')),
                ('sway', models.FloatField(default=0.0, help_text='Perpindahan sway dalam mm')),
                ('total_tilt', models.FloatField(default=0.0, help_text='Total kemiringan dalam derajat')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
