# Generated by Django 4.2.7 on 2026-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(db_index=True, default='DPK', help_text='ID perangkat/site (contoh: CKG-04-031-MM)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device_id', '-timestamp'], name='monitoring__device__2ecaa9_idx'),
        ),
    ]
