# Generated by Django 4.2.28 on 2026-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_sensordata_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='indikator',
            field=models.CharField(choices=[('tolerance', 'Tolerance'), ('intolerance', 'Intolerance')], default='tolerance', help_text='Indikator status: tolerance atau intolerance', max_length=20),
        ),
    ]
