# Generated by Django 4.2.7 on 2026-03-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_sensordata_indikator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='wind_speed_ms',
            field=models.FloatField(default=0.0, help_text='Kecepatan angin dalam m/s'),
        ),
    ]
