# Generated by Django 4.2.7 on 2026-03-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_sensordata_wind_speed_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='ID perangkat/site (contoh: KDS-06-039-MS)', max_length=50, unique=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Apakah site ini disembunyikan dari dashboard?')),
            ],
            options={
                'verbose_name': 'Site Visibility',
                'verbose_name_plural': 'Site Visibilities',
            },
        ),
    ]
