# Generated by Django 4.2.29 on 2026-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_sitevisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(help_text='ID unik site (contoh: ckg-04-031)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama site', max_length=100)),
                ('siteId', models.CharField(help_text='Site ID (contoh: 20TS10B1529)', max_length=50)),
                ('code', models.CharField(help_text='Kode site/device_id (contoh: CKG-04-031-MM)', max_length=50, unique=True)),
                ('lat', models.FloatField(help_text='Latitude')),
                ('lng', models.FloatField(help_text='Longitude')),
                ('area', models.CharField(help_text='Area (contoh: AREA 2)', max_length=50)),
                ('region', models.CharField(help_text='Region', max_length=100)),
                ('kabupaten', models.CharField(help_text='Kabupaten/Kota', max_length=100)),
                ('status', models.CharField(default='online', help_text='Status awal', max_length=20)),
                ('towerType', models.CharField(help_text='Tipe Tower (contoh: SST)', max_length=50)),
                ('towerHeight', models.FloatField(help_text='Tinggi Tower dalam meter')),
                ('isHidden', models.BooleanField(default=False, help_text='Apakah site disembunyikan secara default?')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
