# Generated by Django 4.2.29 on 2026-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(default='offline', help_text='Status awal', max_length=20),
        ),
    ]
